export enum UniqueNameComponents {
    Filter_documentLibraries_dialog = 'Filter_documentLibraries_dialog',
    Send_Or_Reply_dialog = 'Send_Or_Reply_dialog',
    add_Organizations_dialog = 'add_Organizations_dialog',
    add_Or_edit_task_dialog = 'add_Or_edit_task_dialog',
    add_Or_edit_post_dialog = 'add_Or_edit_post_dialog',
    classify_archive_dialog = 'classify_archive_dialog',
    View_Ads_dialog = 'View_Ads_dialog',
    Add_File_dialog = 'Add_File_dialog',
    Add_Session_dialog = 'Add_Session_dialog',
    Add_Test_dialog = 'Add_Test_dialog',
    Add_View_exam_dialog = 'Add_View_exam_dialog',
    Warning_dialog = 'Warning_dialog',
    Copy_Template_dialog = 'Copy_Template_dialog',
    Copy_Class_dialog = 'Copy_Class_dialog',
    Add_Class_dialog = 'Add_Class_dialog',
    Add_Subject_dialog = 'Add_Subject_dialog',
    Add_Supervisor_dialog = 'Add_Supervisor_dialog',
    extendTimeSession_dialog = 'extendTimeSession_dialog',
    Add_Student_dialog = 'Add_Student_dialog',
    Move_Student_dialog = 'Move_Student_dialog',
    Add_Study_Subject_dialog = 'Add_Study_Subject_dialog',
    Add_Unit = 'Add_Unit',
}
